"""change content field to text type

Revision ID: 330c2dabd52d
Revises: ce6713515b2e
Create Date: 2025-08-03 22:53:33.907403

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '330c2dabd52d'
down_revision = 'ce6713515b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogpost', 'content',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogpost', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
