"""fix blog owner

Revision ID: 881b8321bf44
Revises: 5a3726583470
Create Date: 2025-08-03 17:54:59.890406

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '881b8321bf44'
down_revision = '5a3726583470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'blog_owner',
               existing_type=postgresql.ENUM('JOYANGMART', 'PIERROTMART', 'LUCKYCLOUD', name='blogownertype'),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'blog_owner',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=postgresql.ENUM('JOYANGMART', 'PIERROTMART', 'LUCKYCLOUD', name='blogownertype'),
               existing_nullable=False)
    # ### end Alembic commands ###
