"""add post url and id

Revision ID: ce6713515b2e
Revises: 7b01724c36bb
Create Date: 2025-08-03 18:58:14.024705

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ce6713515b2e'
down_revision = '7b01724c36bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogpost', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False))
    op.add_column('blogpost', sa.Column('post_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogpost', 'post_id')
    op.drop_column('blogpost', 'url')
    # ### end Alembic commands ###
